workspace(name = "com_github_Xjs_test_gazelle_fail")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "a82a352bffae6bee4e95f68a8d80a70e87f42c4741e6a448bec11998fcc82329",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.18.5/rules_go-0.18.5.tar.gz"],
)

http_archive(
    name = "bazel_gazelle",
    #sha256 = "3c681998538231a2d24d0c07ed5a7658cb72bfb5fd4bf9911157c0e9ac6a2687",
    #urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz"],
    # use newer than 0.17 to update repo macro while 0.18 is not released yet (minimum is e530fae7ce5cfda701f450ab2d7c4619b87f4df9)
    # IMPORTANT: one version after 39b19ce9 breaks with envoyproxy/protoc-gen-validate - and cost me one day :-(
    urls = ["https://github.com/bazelbuild/bazel-gazelle/archive/39b19ce92c43c9915d69db5fa68b1772434df2e9.zip"],
    sha256 = "e12b1b6bd69544ff0e75d79ed2a99d8326ba3fafe97f8eaf88695e7ad6b37e2a",
    strip_prefix = "bazel-gazelle-39b19ce92c43c9915d69db5fa68b1772434df2e9",
#	urls = ["https://github.com/bazelbuild/bazel-gazelle/archive/master.zip"],
#	strip_prefix = "bazel-gazelle-master",
)


load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
go_rules_dependencies()
go_register_toolchains(nogo = "@//:vet")

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")
gazelle_dependencies()

go_repository(
    name = "com_github_envoyproxy_protoc_gen_validate",
    importpath = "github.com/envoyproxy/protoc-gen-validate",
    sum = "h1:YBW6/cKy9prEGRYLnaGa4IDhzxZhRCtKsax8srGKDnM=",
    version = "v0.0.14",
)
# TODO starting with gazelle e530fae7, repos.bzl can be autogenerated:
# gazelle:repository_macro repos.bzl%go_repositories
#load("//:repos.bzl", "go_repositories")
#go_repositories()
